### ISSUE TITLE
Server disconnected Error due to aiohttp

### ISSUE THREAD

**Issue by y345-git** [AxterDB/wrapper#2]
### Describe the bug

The bug is caused by aiohttp (a library that AxterDB uses). It disconnects the user from the server, giving out the exit like **aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected**

### To Reproduce

**This code can be ran to reproduce the error**

import pwinput
import axterdb
import asyncio
client = axterdb.Client(name="yash345", key="hidden", host="hidden")
# User Functions
class UserFunctions():
    # Initialize
    def __init__(self) -> None:
        pass
    # Find User function
    async def search_user(self):
        print(client._connected)
        await asyncio.sleep(0.01)
        user_query = input("Name the user you want to find: ")
        data = await client.get(table="Password_Manager", username = user_query)
        await asyncio.sleep(0.01)
        if data:
            print(f"{user_query} is present in the database!\n")
            print("Exiting to main menu!")
            await MainClass().main()
        else:
            print(f"{user_query} is not present in the database!\n")
            print("Exiting to main menu!")
            await MainClass().main()

# Main function
class MainClass():
    # Initialize
    def __init__(self) -> None:
        pass
    # Main
    async def main(self):
        if not client._connected:
            await asyncio.sleep(0.01)
            await client.connect()
            await asyncio.sleep(0.01)
        else:
            pass
        table = await client.check_table(table = "Password_Manager")
        await asyncio.sleep(0.01)
        if not table:
            await asyncio.sleep(0.01)
            await client.create_table(table = "Password_Manager", username = "TEXT", password = "TEXT")
            await asyncio.sleep(0.01)
        else:
            pass
        ask = input("""               
    Choose an option:
    1] Find an user
    2] Exit

    Select Option: """
        )   
        if ask == "1":
            await UserFunctions().search_user()
        elif ask == "2":
            exit()
        else:
            print("Enter a valid option!")
            await self.main()
            
# File body
if __name__ == "__main__":
    asyncio.run(MainClass().main())

### Expected behavior

It is expected to connect to the AxterDB server and fetch for the table named "Password_Manager" then go through all the users present in it and display an output of the user is present or not in the db 

### Logs/tracebacks

```python-traceback
1] Find an user
    2] Exit

    Select Option: 1
True
Name the user you want to find: Yash
False
Traceback (most recent call last):
File "c:\Users\HP\Desktop\Python\Under Work\Passwords Manager\report.py", line 64, in <module>
    asyncio.run(MainClass().main())
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
File "c:\Users\HP\Desktop\Python\Under Work\Passwords Manager\report.py", line 55, in main
    await UserFunctions().search_user()
File "c:\Users\HP\Desktop\Python\Under Work\Passwords Manager\report.py", line 15, in search_user
    data = await client.get(table="Password_Manager", username = user_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\axterdb\client.py", line 187, in get
    async with self._session.get(self.route(f"/database/{self.name}/select"), headers=headers, json=data) as response:
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

### Python Version

```console
$ python --version
PS C:\Users\HP\Desktop\Python> python --version
Python 3.11.2
```

### axterdb Version

```console
$ python -m pip show axterdb
PS C:\Users\HP\Desktop\Python> pip show axterdb
Name: axterdb
Version: 1.3
Summary: A Python wrapper for AxterDB
Home-page:
Author: AxterDB Development
Author-email:
License: MIT
Location: C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires:
Required-by:
```

### OS

![image](https://user-images.githubusercontent.com/66121022/231989012-638e44ee-0f42-441e-93ac-3fd4054c9175.png)

**Comment by ItsNeil17** [comment]
Bad reproduce code, please write your own re-produce code next time.
